services:
  spotdown-frontend:
    container_name: spotdown-frontend
    build:
      context: .
      args:
        - VITE_SERVIDOR_API=https://api-spotdown.dryrtan.com
      dockerfile: Dockerfile-frontend
    ports:
      - "7500:3000"
    depends_on:
      - spotdown-backend
    environment:
      NODE_ENV: production

  spotdown-backend:
    container_name: spotdown-backend
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "7501:3001"
    environment:
      NODE_ENV: production
