FROM node:23-alpine3.20
LABEL authors="Dryrtan"

WORKDIR /app
RUN mkdir backend
COPY ./backend /app/backend

RUN apk add --no-cache ffmpeg python3
RUN cd /app/backend && npm install && npx prisma generate

EXPOSE 3001

CMD ["sh", "-c", "node /app/backend/src/index.js"]